services:
  - type: web
    name: iris-predict-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://2026-07-03-python-ai-tvdi.onrender.com
